all: problema1.exe problema2.exe problema3.exe problema4.exe problema5.exe problema6.exe

problema1.exe: problema1.c
	gcc -o problema1.exe problema1.c -g -Wall -lm

problema2.exe: problema2.c
	gcc -o problema2.exe problema2.c -g -Wall -lm

problema3.exe: problema3.c
	gcc -o problema3.exe problema3.c -g -Wall -lm

problema4.exe: problema4.c
	gcc -o problema4.exe problema4.c -g -Wall -lm

problema5.exe: problema5.c
	gcc -o problema5.exe problema5.c -g -Wall -lm

problema6.exe: problema6.c
	gcc -o problema6.exe problema6.c -g -Wall -lm

clear:
	rm *.exe

